- name: Obteniendo repo de Elasticsearch
  yum:
    name: https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/rpm/elasticsearch/2.3.3/elasticsearch-2.3.3.rpm
    state: present

- name: Registrando Elasticsearch como un servicio
  shell: chkconfig --add elasticsearch

- name: Instalando AWS-Cloud Plugin
  shell: /usr/share/elasticsearch/bin/plugin install cloud-aws

- name: Configurando Elasticsearch HEAP_SIZE
  lineinfile:
    path: /etc/sysconfig/elasticsearch
    line: "ES_HEAP_SIZE=256m"

- name: Configurando Elasticsearch MAX_LOCKED_MEMORY
  lineinfile:
    path: /etc/sysconfig/elasticsearch
    line: "MAX_LOCKED_MEMORY=unlimited"

- name: Configurando /etc/elasticsearch/elasticsearch.yml
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    line: "cluster.name: esonaws"

- name: Configurando /etc/elasticsearch/elasticsearch.yml
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    line: "bootstrap.mlockall: true"

- name: Configurando /etc/elasticsearch/elasticsearch.yml
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    line: 'discovery.zen.ping.unicast.hosts: ["{{ hostvars["localhost"]["ec2s"]["instances"][play_hosts.index(inventory_hostname)].private_ip }} ", "{{ hostvars["localhost"]["ec2s"]["instances"][(play_hosts.index(inventory_hostname) + 1) % 3].private_ip }}" , "{{ hostvars["localhost"]["ec2s"]["instances"][(play_hosts.index(inventory_hostname) + 2) % 3].private_ip }}"]'

- name: Configurando /etc/elasticsearch/elasticsearch.yml
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    line: 'network.host:  ["{{ hostvars["localhost"]["ec2s"]["instances"][play_hosts.index(inventory_hostname)].private_ip }}"]'

- name: Iniciando servicio
  service:
    name: elasticsearch
    state: started
